// 單字 excel轉json https://www.bejson.com/json/col2json/
let wordLists = {
    B3L7: [
        { "english": "theory", "chinese": "n. 學說；理論" },
        { "english": "theoretical", "chinese": "adj. 理論上的" },
        { "english": "psychology", "chinese": "n. 心理學" },
        { "english": "psychological", "chinese": "adj. 心理上的" },
        { "english": "demonstrate", "chinese": "vt. 表達；展示" },
        { "english": "demonstration", "chinese": "n. 表達；示範" },
        { "english": "interpret", "chinese": "vt. 理解；詮釋" },
        { "english": "interpretation", "chinese": "n. 解釋；詮釋" },
        { "english": "determine", "chinese": "vt. 查明；測出；決定" },
        { "english": "determination", "chinese": "n. 查明；測出；決心" },
        { "english": "stiff", "chinese": "adj. 僵硬的" },
        { "english": "scratch", "chinese": "vt. 搔抓／n. 刮痕；抓傷" },
        { "english": "exhibit", "chinese": "vt. 表現；表露；展覽" },
        { "english": "exhibition", "chinese": "n. 表現；表露；展覽" },
        { "english": "gesture", "chinese": "n. 手勢；姿勢／vi. 用動作示意" },
        { "english": "moreover", "chinese": "adv. 此外" },
        { "english": "conscious", "chinese": "adj. 意識到；注意到" },
        { "english": "consciousness", "chinese": "n. 意識" },
        { "english": "observe", "chinese": "vt. 觀察" },
        { "english": "observation", "chinese": "n. 觀察" },
        { "english": "reverse", "chinese": "n. 相反的情況或事物／vt. 反轉／adj. 相反的" },
        { "english": "significant", "chinese": "adj. 重要的；顯著的" },
        { "english": "significance", "chinese": "n. 重要性；意義" },
        { "english": "circumstance", "chinese": "n. 條件；狀況" },
        { "english": "initially", "chinese": "adv. 起初" },
        { "english": "initial", "chinese": "adj. 最初的" },
        { "english": "glance", "chinese": "vi. 匆匆一瞥／n. 匆匆一瞥" },
        { "english": "automatically", "chinese": "adv. 無意識地；不假思索地" },
        { "english": "automatic", "chinese": "adj. 自動的" },
        { "english": "track", "chinese": "vt. 追蹤" },
        { "english": "adore", "chinese": "vt. 愛慕；熱愛" },
        { "english": "affection", "chinese": "n. 喜愛" },
        { "english": "interact", "chinese": "vi. 互動；交流" },
        { "english": "interaction", "chinese": "n. 互動" },
        { "english": "meaningful", "chinese": "adj. 有意義的；重要的" },
        { "english": "fellow", "chinese": "adj. 同伴的；同事的／n. 同事；同輩" },
        { "english": "account for", "chinese": "(數量上)佔⋯⋯" },
        { "english": "as well", "chinese": "此外；也" },
        { "english": "in the case of", "chinese": "關於；在⋯⋯的情況下" },
        { "english": "under the circumstances", "chinese": "在這種情況下" },
        { "english": "follow suit", "chinese": "照著做" },
        { "english": "aside from", "chinese": "除了⋯⋯之外" },
        { "english": "best of all", "chinese": "最棒地" }
    ],
    B3L8: [
        { "english": "abuse", "chinese": "n. 虐待／vt. 虐待" },
        { "english": "highlight", "chinese": "n. 最精彩的部分／vt. 強調" },
        { "english": "economy", "chinese": "n. 經濟" },
        { "english": "economic", "chinese": "adj. 經濟上的；經濟學的" },
        { "english": "economical", "chinese": "adj. 節約的；經濟實惠的" },
        { "english": "demand", "chinese": "n. 需求；要求／vt. 要求" },
        { "english": "illegal", "chinese": "adj. 非法的" },
        { "english": "legal", "chinese": "adj. 合法的；法律的" },
        { "english": "herd", "chinese": "n. 獸群" },
        { "english": "lure", "chinese": "vt. 引誘／n. 誘惑；吸引力" },
        { "english": "brutal", "chinese": "adj. 殘暴的" },
        { "english": "mercilessly", "chinese": "adv. 冷酷無情地；殘忍地" },
        { "english": "merciless", "chinese": "adj. 冷酷無情的；殘忍的" },
        { "english": "mercy", "chinese": "n. 仁慈；慈悲" },
        { "english": "operator", "chinese": "n. 經營者" },
        { "english": "operate", "chinese": "vi. 經營；營運" },
        { "english": "operation", "chinese": "n. 營運；業務" },
        { "english": "strike", "chinese": "vt. 打；擊／n. 罷工" },
        { "english": "commit", "chinese": "vt. 做出(錯事)；犯(罪)；承諾；保證" },
        { "english": "commitment", "chinese": "n. 承諾；保證" },
        { "english": "obedient", "chinese": "adj. 服從的；順從的" },
        { "english": "obedience", "chinese": "n. 服從" },
        { "english": "tame", "chinese": "vt. 馴服／adj. 馴服的" },
        { "english": "vulnerable", "chinese": "adj. 脆弱的；容易受傷害的" },
        { "english": "permanent", "chinese": "adj. 永久的" },
        { "english": "adequate", "chinese": "adj. 充足的；足夠的" },
        { "english": "exhaustion", "chinese": "n. 筋疲力盡" },
        { "english": "exhaust", "chinese": "vt. 使筋疲力盡" },
        { "english": "complex", "chinese": "adj. 複雜的" },
        { "english": "intelligent", "chinese": "adj. 聰明的；有才智的" },
        { "english": "intelligence", "chinese": "n. 智力；才智" },
        { "english": "lead to", "chinese": "導致；造成" },
        { "english": "what’s more", "chinese": "此外" },
        { "english": "worse still", "chinese": "更糟的是" },
        { "english": "deal with", "chinese": "解決；處理" },
        { "english": "take pleasure in", "chinese": "以⋯⋯為樂；喜歡做⋯⋯" },
        { "english": "go about", "chinese": "做⋯⋯；忙碌於⋯⋯" }
    ],
    B3L9: [
        { "english": "pilgrimage", "chinese": "n. 朝聖之旅" },
        { "english": "pilgrim", "chinese": "n. 朝聖者；香客" },
        { "english": "unify", "chinese": "vt. 使⋯⋯成為一體；凝聚" },
        { "english": "exaggeration", "chinese": "n. 誇張；誇大" },
        { "english": "exaggerate", "chinese": "vi. 誇張；誇大" },
        { "english": "undoubtedly", "chinese": "adv. 無疑地" },
        { "english": "exact", "chinese": "adj. 精確的" },
        { "english": "authorities", "chinese": "n. 當局；掌權者" },
        { "english": "authority", "chinese": "n. 權力" },
        { "english": "cast", "chinese": "vt. n. 擲；拋／n. 全體演員" },
        { "english": "fade", "chinese": "vi. 逐漸消失" },
        { "english": "throng", "chinese": "n. 聚集的人群；一大群人" },
        { "english": "explosive", "chinese": "adj. 震耳欲聾的" },
        { "english": "explode", "chinese": "vi. vt. 爆炸；引爆" },
        { "english": "explosion", "chinese": "n. 爆炸；爆裂" },
        { "english": "pierce", "chinese": "vt. vi. (光線、聲音等)穿過／vt. 扎；刺穿" },
        { "english": "emerge", "chinese": "vi. 出現" },
        { "english": "blessing", "chinese": "n. 神的祝福" },
        { "english": "bless", "chinese": "vt. 祝福" },
        { "english": "kneel", "chinese": "vi. 跪" },
        { "english": "pavement", "chinese": "n. (鋪過的)路面" },
        { "english": "hospitality", "chinese": "n. 好客" },
        { "english": "hospitable", "chinese": "adj. 好客的" },
        { "english": "enthusiastically", "chinese": "adv. 熱情地" },
        { "english": "enthusiastic", "chinese": "adj. 熱情的" },
        { "english": "enthusiasm", "chinese": "n. 熱情；熱忱" },
        { "english": "facilities", "chinese": "n. 設施" },
        { "english": "facility", "chinese": "n. 場所" },
        { "english": "accommodations", "chinese": "n. 住宿" },
        { "english": "accommodate", "chinese": "vt. 容納" },
        { "english": "religious", "chinese": "adj. 宗教的" },
        { "english": "religion", "chinese": "n. 宗教" },
        { "english": "humanity", "chinese": "n. 人道；仁慈" },
        { "english": "ritual", "chinese": "n. 宗教儀式" },
        { "english": "belief", "chinese": "n. 宗教信仰；相信；信心" },
        { "english": "designate", "chinese": "vt. 指定；認定" },
        { "english": "heritage", "chinese": "n. (一國家或社會所形成的)遺產" },
        { "english": "set out", "chinese": "出發" },
        { "english": "send off", "chinese": "送行" },
        { "english": "in the meantime", "chinese": "期間；同時" },
        { "english": "all manner of", "chinese": "各式各樣的" },
        { "english": "be looking to", "chinese": "試圖⋯⋯" }
    ],
    AMC_Dec_2024: [
        { "english": "effortlessly", "chinese": "adv. 毫不費力地；輕鬆地" },
        { "english": "be traced back to", "chinese": "追溯到" },
        { "english": "artificial", "chinese": "adj. 人工的；人造的" },
        { "english": "mimic", "chinese": "vt. 模仿；模擬" },
        { "english": "practitioner", "chinese": "n. 從事特定活動或職業的人" },
        { "english": "guidance", "chinese": "n. 指導；引導" },
        { "english": "risky", "chinese": "adj. 有風險的；冒險的" },
        { "english": "collector", "chinese": "n. 收集者；收藏家" },
        { "english": "concept", "chinese": "n. 概念；觀念" },
        { "english": "randomly", "chinese": "adv. 隨機地；任意地" },
        { "english": "content", "chinese": "n. 內容(物)；目錄(複數)／含量" },
        { "english": "exceed", "chinese": "v. 超過；勝過" },
        { "english": "uncertainty", "chinese": "n. 不確定(的事物)" },
        { "english": "retail", "chinese": "n. 零售" },
        { "english": "sector", "chinese": "n. 領域；行業；區域" },
        { "english": "virtual", "chinese": "adj. 虛擬的" },
        { "english": "soar", "chinese": "vi. 驟升；高達；翱翔" },
        { "english": "attraction", "chinese": "n. 吸引人的事物；景點" },
        { "english": "associate", "chinese": "v. 聯想；聯繫" },
        { "english": "circuit", "chinese": "n. 迴路；電路；環形物" },
        { "english": "psychological", "chinese": "adj. 心理(學)的" },
        { "english": "peer", "chinese": "n. 同儕；同輩；同行" },
        { "english": "community", "chinese": "n. 群體；社區" },
        { "english": "blossom", "chinese": "vi. 發展；興盛；開花" },
        { "english": "foundation", "chinese": "n. 基礎；地基；基金會" },
        { "english": "maximize", "chinese": "vt. 使最大化" },
        { "english": "limitation", "chinese": "n. 限制" },
        { "english": "evolve", "chinese": "v. 演變；發展" },
        { "english": "adequate", "chinese": "adj. 足夠的" },
        { "english": "input", "chinese": "n. 輸入；投入" },
        { "english": "generate", "chinese": "vt. 生成；產生" },
        { "english": "imitate", "chinese": "vt. 模仿" },
        { "english": "analyze", "chinese": "vt. 分析" },
        { "english": "substitute", "chinese": "n. 替代品" },
        { "english": "intelligence", "chinese": "n. 智慧；才智" },
        { "english": "revolution", "chinese": "n. 革命；變革" },
        { "english": "impactful", "chinese": "adj. 有影響力的；有效的" },
        { "english": "breakthrough", "chinese": "n. 突破；重大進展" },
        { "english": "vast", "chinese": "adj. 廣闊的；巨大的；大量的" },
        { "english": "beneficial", "chinese": "adj. 有益的；有利的" },
        { "english": "pursue", "chinese": "vt. 追求；從事；追趕" },
        { "english": "institute", "chinese": "n. 學院；研究機構" },
        { "english": "prominently", "chinese": "adv. 顯著地；突出地" },
        { "english": "invention", "chinese": "n. 發明(物)；創造" },
        { "english": "innumerable", "chinese": "adj. 無數的；難以計算的" },
        { "english": "primitive", "chinese": "adj. 原始的；早期的" },
        { "english": "coarse", "chinese": "adj. 粗糙的；不光滑的" },
        { "english": "prototype", "chinese": "n. 原型；標準" },
        { "english": "transition", "chinese": "n. 轉變；過渡" },
        { "english": "embark on", "chinese": "開始；著手進行" },
        { "english": "integrate", "chinese": "v. 結合；融為一體" },
        { "english": "generation", "chinese": "n. 世代" },
        { "english": "originate", "chinese": "v. 起源；產生" },
        { "english": "subsequently", "chinese": "adv. 隨後；接著" },
        { "english": "unified", "chinese": "adj. 一致的；統一的" },
        { "english": "technological", "chinese": "adj. 科技的；技術的" },
        { "english": "transmit", "chinese": "v. 傳播；傳染" },
        { "english": "satellite", "chinese": "n. 人造衛星" },
        { "english": "interactive", "chinese": "adj. 互動的；相互作用的" },
        { "english": "mode", "chinese": "n. 方法；方式；模式" },
        { "english": "regardless", "chinese": "adv. 無論如何；不管怎樣" },
        { "english": "stereotype", "chinese": "n. 刻板印象；成見" },
        { "english": "pioneer", "chinese": "v. 開創" },
        { "english": "perception", "chinese": "n. 觀念；看法" },
        { "english": "initiative", "chinese": "n. 倡議；新措施" },
        { "english": "portfolio", "chinese": "n. (某人的)代表作選輯" },
        { "english": "collaborate", "chinese": "vi. 合作" },
        { "english": "component", "chinese": "n. 零件；成分" },
        { "english": "distinguish", "chinese": "v. 區分；分辨" },
        { "english": "universal", "chinese": "adj. 普遍的；共同的" },
        { "english": "compel", "chinese": "vt. 強迫；迫使" },
        { "english": "abolish", "chinese": "vt. 廢除；廢止" },
        { "english": "confrontation", "chinese": "n. 衝突；對抗" },
        { "english": "accusation", "chinese": "n. 指控；譴責" },
        { "english": "discomfort", "chinese": "n. 不適；不安" },
        { "english": "discrimination", "chinese": "n. 歧視" },
        { "english": "amid", "chinese": "prep. 在⋯⋯當中" },
        { "english": "affirm", "chinese": "vt. 證實；聲明；斷言" },
        { "english": "eligible", "chinese": "adj. 具備條件的；有資格的" },
        { "english": "permeate", "chinese": "v. 瀰漫；滲透；充滿" },
        { "english": "anticipation", "chinese": "n. 期望；期待" },
        { "english": "breathtaking", "chinese": "adj. 令人屏息的；驚人的" },
        { "english": "delightful", "chinese": "adj. 令人愉悅的；吸引人的" },
        { "english": "sculpture", "chinese": "n. 雕塑；雕像" },
        { "english": "exterior", "chinese": "adj. 外部的；外表的" },
        { "english": "visual", "chinese": "adj. 視覺的；視力的" },
        { "english": "immerse oneself in", "chinese": "沉浸於；埋首於(事件或體驗)" },
        { "english": "exclusive", "chinese": "adj. 獨有的；豪華的；排外的" },
        { "english": "distressed", "chinese": "adj. 煩亂的；苦惱的" },
        { "english": "resolve", "chinese": "v. 解決" },
        { "english": "promptly", "chinese": "adv. 迅速地" },
        { "english": "alternatively", "chinese": "adv. 要不；或者" },
        { "english": "apology", "chinese": "n. 道歉" },
        { "english": "absolutely", "chinese": "adv. (表示強烈贊同)完全對；絕對地" },
        { "english": "regarding", "chinese": "prep. 關於；至於" },
        { "english": "transit", "chinese": "n. 運輸" },
        { "english": "elsewhere", "chinese": "adv. 在別處" },
        { "english": "update", "chinese": "n. 更新" },
        { "english": "carrier", "chinese": "n. 運輸公司；運送者" },
        { "english": "make up for", "chinese": "彌補；補償" },
        { "english": "perceive", "chinese": "vt. 認為；察覺；感知" },
        { "english": "stinginess", "chinese": "n. 吝嗇；小氣" },
        { "english": "shiver", "chinese": "vi. 發抖；顫抖" },
        { "english": "harsh", "chinese": "adj. 惡劣的；嚴酷的" },
        { "english": "fraud", "chinese": "n. 詐騙；詐欺" },
        { "english": "dismiss", "chinese": "vt. 對⋯⋯不予理會；摒棄" },
        { "english": "reluctantly", "chinese": "adv. 不情願地；勉強地" },
        { "english": "be composed of", "chinese": "由⋯⋯組成" },
        { "english": "compassion", "chinese": "n. 同情；憐憫" },
        { "english": "isolation", "chinese": "n. 孤立；隔離" },
        { "english": "witness", "chinese": "v. 目睹；見證" },
        { "english": "hardship", "chinese": "n. 艱難；困苦" },
        { "english": "possession", "chinese": "n. 所有物；財產；具有" },
        { "english": "grieve", "chinese": "v. 哀悼；悲傷(某人去世)" },
        { "english": "projection", "chinese": "n. 預測；投影" },
        { "english": "vow", "chinese": "v. 發誓；鄭重宣告" },
        { "english": "amend", "chinese": "v. 修改；修訂" },
        { "english": "generosity", "chinese": "n. 慷慨；大方" },
        { "english": "publish", "chinese": "v. 出版；發表" },
        { "english": "literary", "chinese": "adj. 文學的；有關文學的" },
        { "english": "unemployment", "chinese": "n. 失業(率)" },
        { "english": "obligation", "chinese": "n. 義務；責任" },
        { "english": "conviction", "chinese": "n. 堅定的信念；定罪" },
        { "english": "sympathy", "chinese": "n. 同情(心)" },
        { "english": "reform", "chinese": "n. 改革；改造" },
        { "english": "diminish", "chinese": "v. 減少；降低" },
        { "english": "mercy", "chinese": "n. 慈悲；憐憫" },
        { "english": "overwhelm", "chinese": "vt. 使不知所措" },
        { "english": "deficit", "chinese": "n. 不足；虧損" },
        { "english": "core", "chinese": "adj. 核心的" },
        { "english": "distraction", "chinese": "n. 分散注意力的事物" },
        { "english": "systematic", "chinese": "adj. 有條理的；有系統的" },
        { "english": "index", "chinese": "n. 索引" },
        { "english": "concentrate", "chinese": "v. 專注；集中" },
        { "english": "reflection", "chinese": "n. 深思熟慮；反省" },
        { "english": "layout", "chinese": "n. 版面編排；布局；設計" },
        { "english": "revolutionize", "chinese": "vt. 革新；徹底改變" },
        { "english": "distinct", "chinese": "adj. 不同的" },
        { "english": "summarize", "chinese": "v. 總結；概括" },
        { "english": "cue", "chinese": "n. 提示；線索" },
        { "english": "retain", "chinese": "vt. 記住；保留" },
        { "english": "ultimately", "chinese": "adv. 最終；終究" },
        { "english": "comprehension", "chinese": "n. 理解" },
        { "english": "seize", "chinese": "vt. 抓住；奪取" },
        { "english": "discipline", "chinese": "n. 紀律" },
        { "english": "adapt", "chinese": "v. 使適應；調整" },
        { "english": "flourish", "chinese": "v. 興盛；茁壯" },
        { "english": "construction", "chinese": "n. 建築；建造；結構" },
        { "english": "distinctive", "chinese": "adj. 獨特的；與眾不同的" },
        { "english": "abundance", "chinese": "n. 大量；充足" },
        { "english": "option", "chinese": "n. 選擇；選項" },
        { "english": "residence", "chinese": "n. 住所；居住" },
        { "english": "ingenuity", "chinese": "n. 足智多謀；獨創性" },
        { "english": "severe", "chinese": "adj. 劇烈的；慘重的" }
    ]
};